#dockerfile
#使用 nginx最新版本作为基础镜像
FROM nginx
#使用国内源加速，并安装基础的网络工具
RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list \
    && sed -i s@/deb.debian.org/@/mirrors.aliyun.com/@g /etc/apt/sources.list \
	&& sed -i s@/security.debian.org/@/mirrors.aliyun.com/@g /etc/apt/sources.list \
    && apt-get clean\
    && apt-get update \
    && apt-get install -y net-tools \
    && apt-get install -y iputils-ping \
	&& apt-get install -y vim

#将当前文件夹的dist文件复制到容器的/usr/share/nginx/html目录
COPY ./dist /usr/share/nginx/html/
#拷贝.conf文件到nginx分离配置文件目录，在 nginx.conf 文件中会默认引用 conf.d 下的所有配置文件
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

#声明运行时容器暴露的端口（容器提供的服务端口）
EXPOSE 80

#CMD:指定容器启动时要运行的命令
CMD ["nginx", "-g", "daemon off;"]
